<?php

namespace Richpolis\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EdificioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdificioRepository extends EntityRepository
{
}
