<?php

namespace Richpolis\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResidencialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidencialRepository extends EntityRepository
{
}
