<?php

namespace Richpolis\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Richpolis\BackendBundle\Entity\Usuarios;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
    public function queryUsuariosResidencial($residencial){
        $query= $this->getEntityManager()->createQueryBuilder();
        $query->select('u')   
              ->from('Richpolis\BackendBundle\Entity\Usuario', 'u')
              ->leftJoin('u.edificio', 'e')
              ->leftJoin('e.residencial', 'r')
              ->where('r.id=:residencial')
              ->setParameter('residencial', $residencial)
              ->orderBy('u.nombre', 'ASC');
        return $query->getQuery();
    }
	
	public function findUsuariosResidencial($residencial){
        $query = $this->queryUsuariosResidencial($residencial);
		return $query->getResult();
    }
}