Frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

Backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
