#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        Richpolis\BackendBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Richpolis\BackendBundle\Entity\Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: homepage
                always_use_default_target_path: true
            logout:
                path:   logout
                target: login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_SUPER_ADMIN }
        - { path: ^/*, roles: ROLE_USER }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }