#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: homepage
                always_use_default_target_path: true
            logout:
                path: logout
                target: login
            remember_me:
                key:        residenciales1234
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }

    encoders:
        Richpolis\BackendBundle\Entity\Usuario:        { algorithm: sha512, iterations: 10 }


    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: Richpolis\BackendBundle\Entity\Usuario, property: email }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]