# app/config/services.yml
parameters:
    richpolis.controller.aviso.class: Richpolis\FrontendBundle\Controller\AvisoController

services:
    richpolis.aviso.controller:
        class: "%richpolis.controller.aviso.class%"
    
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    login_listener:
        class: Richpolis\FrontendBundle\Listener\LoginListener
        arguments: [@service_container,@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
    