# app/config/services.yml
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

#    login_listener:
#        class: Richpolis\FrontendBundle\Listener\LoginListener
#        arguments: [@service_container,@security.context, @router]
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login }
#            - { name: kernel.event_listener, event: kernel.response }