<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Richpolis\BackendBundle\Entity\Edificio;
use Richpolis\BackendBundle\Entity\Residencial;
use Richpolis\FrontendBundle\Entity\Actividad;
/**
 * ActividadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadesRepository extends EntityRepository
{
    public function queryFindActividadesPorEdificio(Edificio $edificio) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT a,e,r "
                . "FROM FrontendBundle:Actividad a "
                . "JOIN a.edificios e "
                . "JOIN a.residencial r "
                . "WHERE (e.id = :edificio AND a.tipoAcceso=:tipoAccesoEdificio ) "
                . "OR (r.id=:residencial AND a.tipoAcceso=:tipoAccesoResidencial ) "
                . "ORDER BY a.createdAt DESC");
        $consulta->setParameters(array(
            'edificio' => $edificio->getId(),
            'residencial' => $edificio->getResidencial()->getId(),
            'tipoAccesoResidencial'=>Actividad::TIPO_ACCESO_RESIDENCIAL,
            'tipoAccesoEdificio'=>Actividad::TIPO_ACCESO_EDIFICIO,
        ));
        return $consulta;
    }

    public function findActividadesPorEdificio(Edificio $edificio) {
        return $this->queryFindActividadesPorEdificio($edificio)->getResult();
    }
	
	public function queryFindActividadesPorEdificioPorFecha(Edificio $edificio,$month,$year) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT a,e,r "
                . "FROM FrontendBundle:Actividad a "
                . "JOIN a.edificios e "
                . "JOIN a.residencial r "
                . "WHERE (e.id = :edificio AND a.tipoAcceso=:tipoAccesoEdificio ) "
                . "OR (r.id=:residencial AND a.tipoAcceso=:tipoAccesoResidencial ) "
		. "AND a.fechaActividad BETWEEN :inicio AND :fin "
		. "ORDER BY a.createdAt DESC");
        $consulta->setParameters(array(
            'edificio' => $edificio->getId(),
            'residencial' => $edificio->getResidencial()->getId(),
            'tipoAccesoResidencial'=>Actividad::TIPO_ACCESO_RESIDENCIAL,
            'tipoAccesoEdificio'=>Actividad::TIPO_ACCESO_EDIFICIO,
            'inicio'=>"$year-$month-01 00:00:00",
            'fin'=>"$year-$month-31 23:59:59",
        ));
        return $consulta;
    }

    public function findActividadesPorEdificioPorFecha(Edificio $edificio,$month,$year) {
        return $this->queryFindActividadesPorEdificioPorFecha($edificio,$month,$year)->getResult();
    }
    
    public function queryFindActividadesPorResidencial(Residencial $residencial) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT a,e,r "
                . "FROM FrontendBundle:Actividad a "
                . "JOIN a.edificios e "
                . "JOIN a.residencial r "
                . "WHERE r.id =:residencial "
                . "ORDER BY a.createdAt DESC");
        $consulta->setParameters(array(
            'residencial' => $residencial->getId()
        ));
        return $consulta;
    }

    public function findActividadesPorResidencial(Residencial $residencial) {
        return $this->queryFindActividadesPorResidencial($residencial)->getResult();
    }

}
