<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Richpolis\BackendBundle\Entity\Edificio;
use Richpolis\BackendBundle\Entity\Usuario;
use Richpolis\FrontendBundle\Entity\Aviso;

/**
 * AvisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisoRepository extends EntityRepository
{
    public function queryFindAvisosPorEdificio(Edificio $edificio) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT a,e,r "
                . "FROM FrontendBundle:Aviso a "
                . "JOIN a.edificios e "
                . "JOIN a.residencial r "
                . "WHERE (e.id=:edificio OR r.id =:residencial) "
                . "AND a.tipoAcceso<=:tipoAcceso "
                . "ORDER BY a.createdAt DESC");
        $consulta->setParameters(array(
            'edificio' => $edificio->getId(),
            'residencial' => $edificio->getResidencial()->getId(),
            'tipoAcceso' => Aviso::TIPO_ACCESO_EDIFICIO,
        ));
        return $consulta;
    }

    public function findAvisosPorEdificio(Edificio $edificio) {
        return $this->queryFindAvisosPorEdificio($edificio)->getResult();
    }
    
    public function queryFindAvisosPorUsuario(Usuario $usuario) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT a,u,e,r "
                . "FROM FrontendBundle:Aviso a "
                . "JOIN a.usuario u "
                . "JOIN a.edificios e "
                . "JOIN a.residencial r "
                . "WHERE (r.id =:residencial AND a.tipoAcceso=1) "
                . "OR (e.id=:edificio AND a.tipoAcceso=2 ) "
                . "OR (u.id=:usuario AND a.tipoAcceso=3 ) "
                . "ORDER BY a.createdAt DESC");
        $consulta->setParameters(array(
            'usuario' => $usuario->getId(),
            'edificio' => $usuario->getEdificio()->getId(),
            'residencial' => $usuario->getEdificio()->getResidencial()->getId(),
        ));
        return $consulta;
    }

    public function findAvisosPorUsuario(Usuario $usuario,$max = 0) {
        if($max>0){
            return $this->queryFindAvisosPorUsuario($usuario)->setMaxResults($max)->getResult();
        }else{
            return $this->queryFindAvisosPorUsuario($usuario)->getResult();
        }
    }
}
