<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends EntityRepository
{
    public function getReservacionesPorEdificio($edificio_id){
        $em=$this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query
                ->select('i,e,r')
                ->from('Richpolis\FrontendBundle\Entity\Reservacion', 'i')
                ->join('i.edificio', 'e')
                ->join('e.residencial', 'r')
                ->where('e.id=:edificio')
                ->setParameter('edificio', $edificio_id)
                ->orderBy('i.createdAt','DESC')
        ;
        return $query->getResult();
    }
}
