<?php

namespace Richpolis\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Richpolis\BackendBundle\Entity\Edificio;
use Richpolis\BackendBundle\Entity\Usuario;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends EntityRepository
{
    public function queryFindReservacionesPorEdificio(Edificio $edificio) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT s,i,u,e "
                . "FROM FrontendBundle:Reservacion s "
                . "JOIN s.recurso i "
                . "JOIN s.usuario u "
                . "JOIN u.edificio e "
                . "WHERE e.id=:edificio "
                . "ORDER BY s.createdAt DESC");
        $consulta->setParameters(array(
            'edificio' => $edificio->getId(),
        ));
        return $consulta;
    }

    public function findReservacionesPorEdificio(Edificio $edificio) {
        return $this->queryFindReservacionesPorEdificio($edificio)->getResult();
    }
    
    public function queryFindReservacionesPorUsuario(Usuario $usuario) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT s,i,u,e "
                . "FROM FrontendBundle:Reservacion s "
                . "JOIN s.recurso i "
                . "JOIN s.usuario u "
                . "JOIN u.edificio e "
                . "WHERE u.id=:usuario "
                . "ORDER BY s.createdAt DESC");
        $consulta->setParameters(array(
            'usuario' => $usuario->getId(),
        ));
        return $consulta;
    }

    public function findReservacionesPorUsuario(Usuario $usuario) {
        return $this->queryFindReservacionesPorUsuario($usuario)->getResult();
    }
}
